name: Deployment Pipeline

on: [push, pull_request]
     


jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2
          with: 
            fetch-depth: 0
        - uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: Build
          run: npm run build
        - name: Test
          run: npm run test
   