name: Deployment Pipeline

on: [push, pull_request]
     


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with: 
            fetch-depth: 0
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Install dependencies  
          run: npm ci
       
        - name: Build
          run: npm run build
        - name: Test
          run: npm run test
        - name: E2E tests
          uses: cypress-io/github-action@v2
          with:
            command: npm run test:e2e
            start: npm run start-test
            wait-on: http://localhost:5000
   